name: Trigger auto deployment for containerapps-team5

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/containerapps-team5-AutoDeployTrigger-a1b613ab-1f6e-4f46-b78d-373504e952af.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.CONTAINERAPPSTEAM5_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}backend/Dockerfile  
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.CONTAINERAPPSTEAM5_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSTEAM5_REGISTRY_PASSWORD }}
          containerAppName: containerapps-team5
          resourceGroup: 8ai-2nd-team5
          imageToBuild: m86865/m86865/containerapps-team5:${{ github.sha }}
          
            

     

